// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biqsnkemjonjaorlrduj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcXNua2Vtam9uamFvcmxyZHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODMzNzYsImV4cCI6MjA3NDU1OTM3Nn0.1iNPccysAE6aUUjvW6obvLEt-fY5g1mgiNhX023Ld2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});